import {
  formatPrix,
  formatPrixCompact,
  toCamel,
  toSnake,
  isManager,
  getDPEClass,
  getDPEColor,
  STATUTS_MANDAT,
  STATUTS_DEAL,
  TYPES_ACTIF,
  TYPOLOGIES_CLIENT,
  ZONES,
  PORTAILS,
  STATUTS_PORTAIL,
} from '@/lib/crm-constants';
import {
  Field,
  DetailItem,
  KpiCard,
  KpiBox,
  TaskRow,
  AlertRow,
  CommerceBadge,
  StatutBadge,
  DealStatutBadge,
  MaturiteBadge,
  TypeInteractionBadge,
  TaskInline,
  QuickAddTask,
} from '@/components/crm/SharedComponents';
